-- SpringLaunch initial schema.
-- Written to run identically on PostgreSQL and on H2 in PostgreSQL compatibility mode,
-- so the same migrations that run in production are exercised by the test suite.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     VARCHAR(36)  NOT NULL UNIQUE,
    email         VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(160) NOT NULL,
    email_verified BOOLEAN     NOT NULL DEFAULT FALSE,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL
);

CREATE TABLE organizations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          VARCHAR(36)  NOT NULL UNIQUE,
    name               VARCHAR(160) NOT NULL,
    slug               VARCHAR(80)  NOT NULL UNIQUE,
    plan               VARCHAR(20)  NOT NULL DEFAULT 'FREE',
    stripe_customer_id VARCHAR(80) UNIQUE,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL
);

CREATE TABLE memberships (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    organization_id BIGINT      NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    role            VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP   NOT NULL,
    updated_at      TIMESTAMP   NOT NULL,
    CONSTRAINT uk_membership_user_org UNIQUE (user_id, organization_id)
);
CREATE INDEX idx_membership_org ON memberships (organization_id);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(100) NOT NULL UNIQUE,
    expires_at TIMESTAMP    NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL
);
CREATE INDEX idx_refresh_token_user ON refresh_tokens (user_id);

CREATE TABLE subscriptions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id        BIGINT      NOT NULL UNIQUE REFERENCES organizations (id) ON DELETE CASCADE,
    stripe_subscription_id VARCHAR(80) UNIQUE,
    plan                   VARCHAR(20) NOT NULL,
    status                 VARCHAR(30) NOT NULL,
    seats                  INTEGER     NOT NULL DEFAULT 1,
    current_period_end     TIMESTAMP,
    cancel_at_period_end   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMP   NOT NULL,
    updated_at             TIMESTAMP   NOT NULL
);

-- Stripe delivers webhooks at least once; this table makes handling exactly-once.
CREATE TABLE processed_webhook_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(120) NOT NULL UNIQUE,
    event_type  VARCHAR(80)  NOT NULL,
    received_at TIMESTAMP    NOT NULL
);

CREATE TABLE api_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    name            VARCHAR(120) NOT NULL,
    key_prefix      VARCHAR(24)  NOT NULL,
    key_hash        VARCHAR(100) NOT NULL UNIQUE,
    last_used_at    TIMESTAMP,
    revoked_at      TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);
CREATE INDEX idx_api_key_org ON api_keys (organization_id);

CREATE TABLE usage_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    metric          VARCHAR(60) NOT NULL,
    period_key      VARCHAR(7)  NOT NULL,
    quantity        BIGINT      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP   NOT NULL,
    updated_at      TIMESTAMP   NOT NULL,
    CONSTRAINT uk_usage_org_metric_period UNIQUE (organization_id, metric, period_key)
);

CREATE TABLE audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    actor_user_id   BIGINT,
    action          VARCHAR(80)  NOT NULL,
    target          VARCHAR(200),
    detail          VARCHAR(2000),
    created_at      TIMESTAMP    NOT NULL
);
CREATE INDEX idx_audit_org_created ON audit_logs (organization_id, created_at);

-- Example tenant-scoped business resource. Delete it and model your own domain
-- the same way: organization_id column + OrgScopedRepository.
CREATE TABLE projects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       VARCHAR(36)  NOT NULL UNIQUE,
    organization_id BIGINT       NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    name            VARCHAR(160) NOT NULL,
    description     VARCHAR(2000),
    archived        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);
CREATE INDEX idx_project_org ON projects (organization_id);
